
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761
#Stop from Self Register, kyuki ye to main server hai khud serve na hone lge